# Generated by Django 2.0.7 on 2021-01-07 08:53

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('mtitle', models.CharField(max_length=40, verbose_name='音乐名称')),
                ('mpic', models.ImageField(blank=True, null=True, upload_to='df_music/image/%Y/%m', verbose_name='音乐图片')),
                ('mclick', models.IntegerField(default=0, verbose_name='点击量')),
                ('mcontext', tinymce.models.HTMLField(max_length=200, verbose_name='详情')),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲',
            },
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDelete', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=20, verbose_name='分类')),
            ],
            options={
                'verbose_name': '音乐类型',
                'verbose_name_plural': '音乐类型',
            },
        ),
        migrations.AddField(
            model_name='musicinfo',
            name='mtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_music.TypeInfo', verbose_name='分类'),
        ),
    ]
